version: '3.8'
services:
  magicFridge-app:
    build: .
    image: magicfridge-app:0.0.1-RELEASE
    container_name: magicfridge-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}