CREATE TABLE food_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome       VARCHAR(255)                            NOT NULL,
    categoria  VARCHAR(255)                            NOT NULL,
    quantidade INTEGER                                 NOT NULL,
    validade   date                                    NOT NULL,
    CONSTRAINT pk_food_item PRIMARY KEY (id)
);